quarkus:
  http:
    port: 24188
  transaction-manager:
    default-transaction-timeout: PT1H

  log:
    category:
      #"org.apache.shiro":
      #  level: DEBUG
      "com.dropchop":
        level: DEBUG

  compose:
    devservices:
      files: src/main/docker/compose-devservices-test.yaml
